server:
  port: 8080

spring:
  application:
    name: ms-client
  data:
    mongodb:
      database: msclient
      host: localhost
      port: 27017
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoint:
    health:
      probes.enabled: true
