application:
  consume:
    client:
      url: http://localhost:8080/client
spring:
  application:
    name: ms-debitcard
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: consumer
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      database: msdebitcard
      port: '27017'
      host: localhost
server:
  port: '8089'
properties:
  config:
    server: 'true'
